### ISSUE TITLE
Link new pages to site

### ISSUE THREAD

**Issue by hadinh1306** [kishaningithub/hugo-creative-portfolio-theme#37]
I cannot find a way to link new page to the website I built with this theme. Can you help explain the process?

**Comment by kishaningithub** [comment]
HI @hadinh1306 Just to clarify, by new page do you mean a new portfolio or a new page itself like about and contact ?

**Comment by kishaningithub** [comment]
## For new Portfolio

Run `hugo new portolio/portfolio1.md`

## For new page

You can't do it (yet...)

Can you let me know on why you want that feature ?

**Comment by kishaningithub** [comment]
@hadinh1306 Any updates?

**Comment by hadinh1306** [comment]
Hi @kishaningithub, 

So sorry for not updating you about this earlier. I figured out how to get it to work. It was easier than I thought. I added `type: "post"` in my initial Rmd setting. 

I still have 1 problem though. I cannot make it to work with `https`. It doesn't load css settings when I open my website. I guess it's more a problem with my hosting service. If you have encountered this before, or have any idea how to solve this, please let me know! I will move this to a new issue. 

Thank you!

**Comment by kishaningithub** [comment]
Hi @hadinh1306 Could you point me to your site so that i can help debug? 

From what is guess, The problem would most likely be that somehow the CSS could be loaded via http while the base site was loaded with https. Changing the `baseurl` property in your `config.toml` from say `http://example.org/` to `https://example.org/` should fix this issue.

**Comment by kishaningithub** [comment]
@hadinh1306 Were you able to fix the issue?
