### ISSUE TITLE
Unable to find theme Directory

### ISSUE THREAD

**Issue by graham768** [kishaningithub/hugo-creative-portfolio-theme#67]
I cloned the repo and tried to build the site using `hugo -v --source exampleSite` from your travis config script, but received the error 
`Error: Unable to find theme Directory: ~hugo-creative-portfolio-theme/exampleSite/themes/hugo-creative-portfolio-theme`

I also tried downgrading my hugo installation from 0.55.6 to 0.40.3 to match the travis build in case themes weren't required previously, but no luck.

If I'm missing a step, let's add it to the README.

This could also be related to [your issue](https://github.com/gohugoio/hugoThemes/issues/649) on the hugoThemes page

**Comment by kishaningithub** [comment]
@graham768  This issue is exactly what it says. The exampleSite expects the theme directory to be present within it. That's how hugo works. So there are 2 options here

- Symlink the parent theme directory within the exampleSite directory (This is what all the theme authors do for theme development)
- Clone/Copy the theme directory within the example site. This is exactly what i did in the travis build.
```
  - git clone --depth 1 https://github.com/kishaningithub/hugo-creative-portfolio-theme.git exampleSite/themes/hugo-creative-portfolio-theme
  - ./tools/hugo -v --source exampleSite
```
The first command clones the theme into `exampleSite/themes` directory and the second one starts the example site

**Comment by kishaningithub** [comment]
@graham768 Also i just upgraded hugo to 0.55.6 in commit [9a9dc3fd4e9a144f0b17cb9d703890c328aa31c6](https://github.com/kishaningithub/hugo-creative-portfolio-theme/commit/9a9dc3fd4e9a144f0b17cb9d703890c328aa31c6) and the build was successful.

Do let me know if something is not clear from my previous comment. Happy to help.
